import "../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
export const metadata = {
  title: "Arrays Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({ children  ,params: locale}) {
  const messages = await getMessages(locale)
  return (
    <html lang={locale}>
      <body className={` dark:bg-dark`}>
        <NextIntlClientProvider messages={messages}>
        <div>  
          {children}

        </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
